-- This file was automatically generated by M22toLua v0.7.0
-- For use with March22-Lua
-- By Sam Lynch

dofile("app0:/LUA_CLASSES/Line.lua");
dofile("app0:/March22_background.lua");


LOADEDSFX = {};
LOADEDMUSIC = {};
LABEL_POSITIONS = {};
March22.CURRENTSCRIPTNAME = "test2.m22.lua";

LABEL_POSITIONS["start"] = 1;



ACTIVE_SCRIPT = {
	Line.new("", March22.WHITE_COLOUR, "", function() --[[ start ]] end),
	Line.new("", March22.WHITE_COLOUR, "SetActiveTransition Fade"),
	Line.new("", March22.WHITE_COLOUR, "", function() ChangeBackground("bedroom_night");March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "…"),
	Line.new("", March22.WHITE_COLOUR, "I can't sleep."),
	Line.new("", March22.WHITE_COLOUR, "Usually people can't sleep because they're excited, anxious, or even scared. Except the closest feeling I can equate to right now is one of confusion. That, and all of the above. Not that I'd ever admit it to anyone."),
	Line.new("", March22.WHITE_COLOUR, "I roll over in my not-very-comfortable dorm-room bed, springs poking into my hip as I settle, and open my eyes slowly to evaluate the readout from my digital alarm clock."),
	Line.new("", March22.WHITE_COLOUR, "\"4:20am\" it reads."),
	Line.new("", March22.WHITE_COLOUR, "Damn."),
	Line.new("", March22.WHITE_COLOUR, "I was hoping- clearly in futility- that the time would at least be somewhat close to when I have to get out of bed anyway, putting an end to this ridiculous attempt to fall asleep, and I can go to my new classes. The classes for gifted students."),
	Line.new("", March22.WHITE_COLOUR, "NewPage"),
	Line.new("", March22.WHITE_COLOUR, "I, [MC_FIRSTNAME] [MC_LASTNAME], a gifted student, taking classes for gifted students. Not entirely sure how this came about but I'll try my best to collect my memory. "),
	Line.new("", March22.WHITE_COLOUR, "Essentially, I took the same standardised tests as the rest of the country at the end of middle school. English, Science, History… and Math. Apparently my performance in mathematics warranted a scholarship to a boarding school for the \"exceptionally gifted\". "),
	Line.new("", March22.WHITE_COLOUR, "Now, I'm not being modest here; I genuinely just enjoy maths. "),
	Line.new("", March22.WHITE_COLOUR, "Can it even be called enjoyment? I guess I just didn't hate it, like my friends. "),
	Line.new("", March22.WHITE_COLOUR, "I never analysed why, nor did I give a second thought to why I was good at it. I would frequently finish the provided exercises, so the teacher would provide me with some more \"challenging\" material. "),
	Line.new("", March22.WHITE_COLOUR, "I remember my teacher's face as I handed him back the completed extension exercises, mere minutes after being provided them."),
	Line.new("", March22.WHITE_COLOUR, "So, when I received the 'summons' to the headmaster's office, the only reason that could occur to me was that I'd gotten a mark less than 100. "),
	Line.new("", March22.WHITE_COLOUR, "But boy, was it more than that. "),
	Line.new("", March22.WHITE_COLOUR, "", function() ChangeBackground("oldschool_principle_office");March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "DarkenScreen"),
	Line.new("", March22.WHITE_COLOUR, "", function() March22.PlayTrack("Fripperies");March22.NextLine(); end ),
	Line.new("", March22.WHITE_COLOUR, "NewPage"),
	Line.new("", March22.WHITE_COLOUR, "// =================================================="),
	Line.new("", March22.WHITE_COLOUR, "He guided me into his office, and I remember him offering me tea or coffee, as if I were a colleague, so I automatically could tell that it was regarding something that made the school- and by extension, him- look good. "),
	Line.new("", March22.WHITE_COLOUR, "He was a burly man, always wearing a suit with a belt that seemed to make his pot-belly stick out further than thought possible. He wore thin, rectangular reading glasses and a brown, diamond-patterned tie to match the colour of his suit."),
	Line.new("", March22.WHITE_COLOUR, "\"Your talents in mathematics have not gone unnoticed,\" I recall him saying. \"I know it's a big ocean of young talent out there, especially for a sardine such as yourself, and it's a very big fish that has noticed you.\""),
	Line.new("", March22.WHITE_COLOUR, "Sardines? Ocean? What?"),
	Line.new("", March22.WHITE_COLOUR, "\"You see, a very, very privileged boarding school has taken a fancy to your particular ability in mathematics,\" he said to me. "),
	Line.new("", March22.WHITE_COLOUR, "\"They're prepared to offer a full scholarship, with free education and accommodation. It is akin to any other in its curriculum, except in the aspect that it provides the specialist education that would allow your talent to really shine.\""),
	Line.new("", March22.WHITE_COLOUR, "NewPage"),
	Line.new("", March22.WHITE_COLOUR, "// =================================================="),
	Line.new("", March22.WHITE_COLOUR, "So… harder homework?"),
	Line.new("", March22.WHITE_COLOUR, "\"No, no,\" he laughed in reply. \"It's a bit more than that.\" "),
	Line.new("", March22.WHITE_COLOUR, "\"If your talent was in art, for example, you could arrange the colours of paint they have into a rainbow that'd cover the baseball field. If it were chemistry, you could study many more reactions than simply antacids and cola.\""),
	Line.new("", March22.WHITE_COLOUR, "So with Math, we get bigger whiteboards? This isn't exactly a great sales pitch."),
	Line.new("", March22.WHITE_COLOUR, "\"I would imagine that the budget given to their maths department gets funnelled into providing some stellar teaching staff, as you are quite correct; there isn't much to provide mathematicians such as yourself!\""),
	Line.new("", March22.WHITE_COLOUR, "I don't say this to him, but it does make me feel good to hear him say this."),
	Line.new("", March22.WHITE_COLOUR, "\"You'll take the same subjects as you would at any other high school,\" he says while rubbing the lens of his glasses with his shirt. "),
	Line.new("", March22.WHITE_COLOUR, "\"Except for extended classes for your talent- in this case, mathematics.\" He points at me with his glasses before returning them to his face."),
	Line.new("", March22.WHITE_COLOUR, "NewPage"),
	Line.new("", March22.WHITE_COLOUR, "// =================================================="),
	Line.new("", March22.WHITE_COLOUR, "\"I understand that this might be a difficult decision to make, as it would mean being separated from your family and friends for an extended period of time, as well as your friends moving on to other pastures.\""),
	Line.new("", March22.WHITE_COLOUR, "What's that about pastures? What happened to the ocean metaphors?"),
	Line.new("", March22.WHITE_COLOUR, "As I thought about it then, it occurred to me that I actually didn't mind. "),
	Line.new("", March22.WHITE_COLOUR, "My friends were still friends, but I think we were friends out of necessity; as if our middle-school survival depended on it. "),
	Line.new("", March22.WHITE_COLOUR, "'Birds of a feather flock together,' I remember seeing somewhere. "),
	Line.new("", March22.WHITE_COLOUR, "Apt; we just clung together so as to not be alone. "),
	Line.new("", March22.WHITE_COLOUR, "It was depressing to think about, frankly."),
	Line.new("", March22.WHITE_COLOUR, "\"But I highly encourage you to seize this opportunity. Graduating from Kingshead College practically guarantees you a position at any university you desired, not to mention receiving an unrivalled education.\""),
	Line.new("", March22.WHITE_COLOUR, "Kingshead?"),
	Line.new("", March22.WHITE_COLOUR, "\"Yes, that's the name of the school. I think I have a pamphlet somewhere…\""),
	Line.new("", March22.WHITE_COLOUR, "NewPage"),
	Line.new("", March22.WHITE_COLOUR, "// =================================================="),
	Line.new("", March22.WHITE_COLOUR, "He fumbled with the drawers of his desk until he clearly found what he was looking for, and handed me what could barely be called a pamphlet. "),
	Line.new("", March22.WHITE_COLOUR, "It was more like a handbook, and printed on a type of paper that just screams 'we have more money than we know what to do with.' "),
	Line.new("", March22.WHITE_COLOUR, "I flipped through the handbook briefly, since it'd take far longer than what time me and the principal had to read it thoroughly there and then. "),
	Line.new("", March22.WHITE_COLOUR, "The photographs, even taken with a pinch of salt, still betray an aura of privilege. "),
	Line.new("", March22.WHITE_COLOUR, "This was all I was really looking at in the expensive-to-print handbook-slash-'pamphlet', since there wasn't much else to ask about; I'd be a fool to turn down such an opportunity. "),
	Line.new("", March22.WHITE_COLOUR, "There's nothing tying me here, so why stay?"),
	Line.new("", March22.WHITE_COLOUR, "\"Kingshead…\""),
	Line.new("", March22.WHITE_COLOUR, "He smiles at me, asking my thoughts. I look up from the pamphlet to his smiling complexion."),
	Line.new("", March22.WHITE_COLOUR, "NewPage"),
	Line.new("", March22.WHITE_COLOUR, "// =================================================="),
	Line.new("", March22.WHITE_COLOUR, "\"When can I start?\" I said."),
	Line.new("", March22.WHITE_COLOUR, "FadeToBlackFancy"),
	Line.new("", March22.WHITE_COLOUR, "NewPage"),
	Line.new("", March22.WHITE_COLOUR, "// =================================================="),
	Line.new("", March22.WHITE_COLOUR, "LoadScript chapter_2.txt")
};
UpdateLoadingProgress(100);
SIZE_OF_ACTIVE_SCRIPT = 69;
