-- This file was automatically generated by RPYtoLua
-- For use with March22-Lua
-- By Sam Lynch

LABELS = {};

attraction_sc = 0;
attraction_hanako = 0;
attraction_kenji = 0;




LABELS["imachine"] = {
	function() 	jump_out ("NOP1"); end
};

LABELS["NOP1"] = {
	function() 	iscene("NOP1"); end,
	function() 	jump_out ("op_video"); end
};

LABELS["op_video"] = {
	function() 	iscene("op_vid1"); end,
	function() 	jump_out ("NOP2"); end
};

LABELS["NOP2"] = {
	function() 	iscene("NOP2"); end,
	function() 	jump_out ("tc_act1"); end
};

LABELS["tc_act1"] = {
	function() 	act_op("tc_act1.mkv"); end,
	function() 	jump_out ("A1"); end
};

LABELS["A1"] = {
	function() 	iscene("A1"); end,
	function() 	imenu("choiceA1"); end,
	function() 
	if _return == m1 then

		iscene("A1a")
	else
		 attraction_sc = attraction_sc +  1
		iscene("A1b")
	end; end,
	function() 	iscene("A1c"); end,
	function() 	jump_out ("A2"); end
};

LABELS["A2"] = {
	function() 	iscene("A2"); end,
	function() 
	if seen_scene("A1a") then

		iscene("A2a")
	else
		iscene("A2b")
	end; end,
	function() 	iscene("A2c"); end,
	function() 
	if seen_scene("A1b") then

		iscene("A2d")
	else
		iscene("A2e")
	end; end,
	function() 	iscene("A2f"); end,
	function() 	jump_out ("A3"); end
};

LABELS["A3"] = {
	function() 	iscene("A3"); end,
	function() 	imenu("choiceA3"); end,
	function() 
	if _return == m1 then

		 attraction_hanako = attraction_hanako +  1
		iscene("A3a")
	elseif _return == m2 then
		iscene("A3b")
	else
		 attraction_sc = attraction_sc +  1
		iscene("A3c")
	end; end,
	function() 	iscene("A3d"); end,
	function() 	jump_out ("A4"); end
};

LABELS["A4"] = {
	function() 	iscene("A4"); end,
	function() 	jump_out ("A5"); end
};

LABELS["A5"] = {
	--function() 	iscene("timeskip"); end,
	function() 	iscene("A5"); end,
	function() 	jump_out ("A6"); end
};

LABELS["A6"] = {
	function() 	iscene("A6"); end,
	function() 	imenu("choiceA6"); end,
	function() 
	if _return == m1 then

		 attraction_sc = attraction_sc +  1
		iscene("A6a")
	else
		iscene("A6b")
	end; end,
	function() 	iscene("A6c"); end,
	function() 	jump_out ("A7"); end
};

LABELS["A7"] = {
	function() 	iscene("A7"); end,
	function() 	jump_out ("A8"); end
};

LABELS["A8"] = {
	function() 	iscene("A8"); end,
	function() 	imenu("choiceA8"); end,
	function() 
	if _return == m1 then

		iscene("A8a")
		if seen_scene("A1b") then

			iscene("A8aa")
		end
	else
		 attraction_hanako = attraction_hanako + 1
		iscene("A8b")
	end; end,
	function() 	iscene("A8c"); end,
	function() 
	if seen_scene("A8a") then

		iscene("A8d")
	else
		iscene("A8e")
	end; end,
	function() 	iscene("A8f"); end,
	function() 	jump_out ("A9"); end
};

LABELS["A9"] = {
	function() 	iscene("A9"); end,
	function() 	imenu("choiceA9"); end,
	function() 
	if _return == m1 then

		 attraction_hanako = attraction_hanako +  1
		iscene("A9a")
	else
		iscene("A9b")
	end; end,
	function() 	iscene("A9c"); end,
	function() 	jump_out ("A10"); end
};

LABELS["A10"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("A10"); end,
	function() 
	if attraction_sc > 1 and attraction_hanako > 1 then

		imenu("choiceA10a")
		if _return == m1 then

			iscene("A10a")
		elseif _return == m2 then
			iscene("A10b")
			jump_out ("A11_2")
		else
			iscene("A10c")
		end
		imenu("choiceA10b")
		if _return == m1 then

			iscene("A10c")
		else
			iscene("A10a")
		end
		imenu("choiceA10c")
		if _return == m1 then

			iscene("A10a")
		else
			iscene("A10b")
			jump_out ("A11_2")
		end
		iscene("A10a")
	end; end,
	function() 	jump_out ("A11_1"); end
};

LABELS["A11_1"] = {
	function() 	iscene("A11"); end,
	function() 	iscene("A11a"); end,
	function() 	iscene("A11b"); end,
	function() 
	if seen_scene("A10c") then

		iscene("A11x")
		jump_out ("A12")
	end; end,
	function() 	iscene("A11y"); end,
	function() 	jump_out ("A15"); end
};

LABELS["A11_2"] = {
	function() 	iscene("A11c"); end,
	function() 	iscene("A11a"); end,
	function() 	iscene("A11d"); end,
	function() 	jump_out ("A13"); end
};

LABELS["A12"] = {
	function() 	iscene("A12"); end,
	function() 	jump_out ("A16") ; end
};

LABELS["A13"] = {
	function() 	iscene("A13"); end,
	function() 	jump_out ("A15"); end
};

LABELS["A15"] = {
	function() 	iscene("A15"); end,
	function() 	jump_out ("A16"); end
};

LABELS["A16"] = {
	function() 	iscene("A16"); end,
	function() 	jump_out ("A17"); end
};

LABELS["A17"] = {
	function() 	iscene("A17"); end,
	function() 	imenu("choiceA17"); end,
	function() 
	if _return == m1 then

		iscene("A17a")
	else
		iscene("A17b")
	end; end,
	function() 	iscene("A17c"); end,
	function() 	jump_out ("A18"); end
};

LABELS["A18"] = {
	function() 	iscene("A18"); end,
	function() 	jump_out ("A19"); end
};

LABELS["A19"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("A19"); end,
	function() 
	if seen_scene("A17a") then

		iscene("A19a")
	else
		iscene("A19b")
	end; end,
	function() 	iscene("A19c"); end,
	function() 
	if seen_scene("A11b") then

		iscene("A19i")
	end; end,
	function() 	iscene("A19j"); end,
	function() 
	if seen_scene("A17a") then

		iscene("A19d")
	else
		iscene("A19e")
	end; end,
	function() 	iscene("A19f"); end,
	function() 
	if seen_scene("A17a") then

		iscene("A19g")
	else
		iscene("A19h")
	end; end,
	function() 	jump_out ("A20"); end
};

LABELS["A20"] = {
	function() 	iscene("A20"); end,
	function() 	jump_out ("A21"); end
};

LABELS["A21"] = {
	function() 	iscene("A21"); end,
	function() 	imenu("choiceA21"); end,
	function() 
	if _return == m1 then

		iscene("A21a")
		jump_out ("A22")
	end; end,
	function() 	iscene("A21b"); end,
	function() 
	if seen_scene("A13") then

		iscene("A21c")
	else
		iscene("A21d")
	end; end,
	function() 	jump_out ("A23"); end
};

LABELS["A22"] = {
	function() 	iscene("A22"); end,
	function() 
	if not seen_scene("A12") then

		iscene("A22a")
		jump_out ("A23")
	end; end,
	function() 	jump_out ("A22_2"); end
};

LABELS["A22_2"] = {
	function() 	iscene("A22b"); end,
	function() 
	if seen_scene("A21c") then

		jump_out ("A24")
	end; end,
	function() 	jump_out ("A24_1"); end
};

LABELS["A23"] = {
	function() 
	if not seen_scene("A22a") then

		jump_out ("A23_1")
	end; end,
	function() 
	if not seen_scene("A21c") then

		jump_out ("A23_2")
	end; end,
	function() 	jump_out ("A24") ; end
};

LABELS["A23_1"] = {
	function() 	iscene("A23"); end,
	function() 
	if seen_scene("A21c") then

		jump_out ("A24")
	end; end,
	function() 	jump_out ("A23_2"); end
};

LABELS["A23_2"] = {
	function() 	iscene("A23a"); end,
	function() 
	if seen_scene("A21c") then

		jump_out ("A24")
	end; end,
	function() 	jump_out ("A24_1"); end
};

LABELS["A24"] = {
	function() 	iscene("A24"); end,
	function() 
	if seen_scene("A21a") then

		iscene("A24c")
	else
		iscene("A24d")
	end; end,
	function() 	iscene("A24e"); end,
	function() 	jump_out ("A24_1"); end
};

LABELS["A24_1"] = {
	function() 
	if seen_scene("A17a") then

		iscene("A24a")
		jump_out ("A25")
	end; end,
	function() 	iscene("A24b"); end,
	function() 	jump_out ("A26"); end
};

LABELS["A25"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("A25"); end,
	function() 	imenu("choiceA25"); end,
	function() 
	if _return == m1 then

		iscene("A25b")
		jump_out ("A27")
	end; end,
	function() 	iscene("A25a"); end,
	function() 	jump_out ("A26"); end
};

LABELS["A26"] = {
	function() 
	if not seen_scene("A25") then

		iscene("timeskip")
		iscene("A26")
	end; end,
	function() 	iscene("A26a"); end,
	function() 
	if not seen_scene("A22b") then

		iscene("A26e")
		jump_out ("A27_2")
	end; end,
	function() 	jump_out ("A26_1"); end
};

LABELS["A26_1"] = {
	function() 	iscene("A26b"); end,
	function() 	imenu("choiceA26"); end,
	function() 
	if _return == m1 then

		iscene("A26c")
		jump_out ("A28")
	end; end,
	function() 	 attraction_kenji = attraction_kenji +  1; end,
	function() 	iscene("A26d"); end,
	function() 	jump_out ("A27_2"); end
};

LABELS["A27"] = {
	function() 	iscene("A27"); end,
	function() 
	if seen_scene("A22b") then

		jump_out ("A27_1")
	end; end,
	function() 	iscene("A27e"); end,
	function() 	jump_out ("A29"); end
};

LABELS["A27_1"] = {
	function() 	iscene("A27a"); end,
	function() 	imenu("choiceA27"); end,
	function() 
	if _return == m1 then

		iscene("A27b")
		 attraction_kenji = attraction_kenji +  1
		iscene("A27f")
		jump_out ("A29") 
	end; end,
	function() 	iscene("A27c"); end,
	function() 
	if seen_scene("A25b") then

		imenu("choice2A27")
		if _return == m1 then

			iscene("A27h")
			iscene("A27e")
			jump_out ("A29")									 
		end
	end; end,
	function() 	jump_out ("A28"); end
};

LABELS["A27_2"] = {
	function() 	iscene("A27d"); end,
	function() 
	if seen_scene("A26d") then

		iscene("A27f")
	else
		iscene("A27e")
	end; end,
	function() 	jump_out ("A29"); end
};

LABELS["A28"] = {
	function() 	iscene("A28"); end,
	function() 
	if seen_scene("A26c") then

		iscene("A28a")
	end; end,
	function() 	iscene("A28b"); end,
	function() 	jump_out ("A36"); end
};

LABELS["A29"] = {
	function() 
	if not seen_scene("A25b") then

		iscene("A29")
		if seen_scene("A27f") then

			iscene("A29x")
		end
		iscene("A29a")
	end; end,
	function() 	iscene("A29b"); end,
	function() 
	if seen_scene("A25b") then

		iscene("A29c")
		jump_out ("A31")
	end; end,
	function() 	jump_out ("A30"); end
};

LABELS["A30"] = {
	function() 	iscene("A30"); end,
	function() 
	if seen_scene("A26d") or seen_scene("A27b") then

		iscene("A30a")
		jump_out ("A31")
	end; end,
	function() 	imenu("choiceA30"); end,
	function() 
	if _return == m2 then

		 attraction_kenji = attraction_kenji +  1
		iscene("A30a")
		jump_out ("A31")
	end; end,
	function() 	iscene("A30b"); end,
	function() 
	if seen_scene("A11c") then

		iscene("A30c")
	end; end,
	function() 	iscene("A30d"); end,
	function() 	jump_out ("A31"); end
};

LABELS["A31"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("A31"); end,
	function() 
	if seen_scene("A25b") then

		iscene("A31b")
	else
		iscene("A31c")
	end; end,
	function() 	iscene("A31d"); end,
	function() 
	if attraction_kenji > 0 then

		iscene("A31e")
		jump_out ("A38")
	elseif seen_scene("A29c") then
		jump_out ("A32")
	elseif seen_scene("A24d") then
		jump_out ("A35")
	end; end,
	function() 	jump_out ("A32"); end
};

LABELS["A32"] = {
	function() 	iscene("A32"); end,
	function() 
	if seen_scene("A23a") then

		iscene("A32a")
	end; end,
	function() 	iscene("A32b"); end,
	function() 
	if seen_scene("A25b") then

		jump_out ("A34")
	end; end,
	function() 	jump_out ("A33"); end
};

LABELS["A33"] = {
	function() 	iscene("A33"); end,
	function() 	imenu("choiceA33"); end,
	function() 
	if _return == m2 then

		iscene("A33a")
	else
		iscene("A33b")
	end; end,
	function() 	jump_out ("A38"); end
};

LABELS["A34"] = {
	function() 	iscene("A34"); end,
	function() 	iscene("A34a"); end,
	function() 	jump_out ("A38"); end
};

LABELS["A35"] = {
	function() 	iscene("A35"); end,
	function() 	imenu("choiceA35"); end,
	function() 
	if _return == m1 then

		iscene("A35a")
		jump_out ("A38")
	end; end,
	function() 	jump_out ("A37"); end
};

LABELS["A36"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("A36"); end,
	function() 	jump_out ("A38"); end
};

LABELS["A37"] = {
	function() 	iscene("A37"); end,
	function() 	jump_out ("A38"); end
};

LABELS["A38"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("A38"); end,
	function() 
	if seen_scene("A31e") then

		jump_out ("A43")
	elseif seen_scene("A36") then
		iscene("A38a")
		iscene("A38e")
		jump_out ("A44")
	elseif seen_scene("A35") or seen_scene("A37") then
		iscene("A38b")
		iscene("A38e")
		if seen_scene("A37") then

			jump_out ("A42")
		end
	elseif seen_scene("A33a") then
		iscene("A38c")
		iscene("A38e")
		jump_out ("A40")
	elseif seen_scene("A34") then
		iscene("A38d")
		iscene("A38e")
		jump_out ("A39")
	end; end,
	function() 	jump_out ("A43"); end
};

LABELS["A39"] = {
	function() 	iscene("A39"); end,
	function() 	jump_out ("tc_act2_emi"); end
};

LABELS["A40"] = {
	function() 	iscene("A40"); end,
	function() 	jump_out ("tc_act2_rin"); end
};

LABELS["A41"] = {
	function() 	iscene("A41b"); end,
	function() 	iscene("A41a"); end,
	function() 	jump_out ("tc_act2_lilly"); end
};

LABELS["A42"] = {
	function() 	iscene("A41b"); end,
	function() 	iscene("A42"); end,
	function() 	jump_out ("H2"); end
};

LABELS["A43"] = {
	function() 	iscene("A43"); end,
	function() 	path_end(); end,
	function() 	jump_out ("restart"); end
};

LABELS["A44"] = {
	function() 	iscene("A44"); end,
	function() 	jump_out ("tc_act2_shizune"); end
};

LABELS["H2"] = {
	function() 	iscene("H2"); end,
	function() 	jump_out ("tc_act2_hanako"); end
};

LABELS["tc_act2_hanako"] = {
	function() 	act_op("tc_act2_hanako.mkv"); end,
	function() 	jump_out ("H3"); end
};

LABELS["H3"] = {
	function() 	iscene("H3"); end,
	function() 	jump_out ("H4"); end
};

LABELS["H4"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("H4"); end,
	function() 	imenu("choiceH4"); end,
	function() 
	if _return == m1 then

		jump_out ("H5_1")
	else
		jump_out ("H5_2")
	end; end
};

LABELS["H5_1"] = {
	function() 	iscene("H5_1"); end,
	function() 	jump_out ("H6"); end
};

LABELS["H5_2"] = {
	function() 	iscene("H5_2"); end,
	function() 	jump_out ("H6"); end
};

LABELS["H6"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("H6"); end,
	function() 	jump_out ("H7"); end
};

LABELS["H7"] = {
	function() 	iscene("H7"); end,
	function() 
	if seen_scene("H5_1") then

		iscene("H7a")
	elseif seen_scene("H5_2") then
		iscene("H7b")
	end; end,
	function() 	iscene("H7c"); end,
	function() 	jump_out ("H8"); end
};

LABELS["H8"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("H8"); end,
	function() 	jump_out ("H9"); end
};

LABELS["H9"] = {
	function() 	iscene("H9"); end,
	function() 	jump_out ("H10"); end
};

LABELS["H10"] = {
	function() 	iscene("H10"); end,
	function() 	jump_out ("tc_act3_hanako"); end
};

LABELS["tc_act3_hanako"] = {
	function() 	act_op("tc_act3_hanako.mkv"); end,
	function() 	jump_out ("H11"); end
};

LABELS["H11"] = {
	function() 	iscene("H11"); end,
	function() 	jump_out ("H12"); end
};

LABELS["H12"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("H12"); end,
	function() 	imenu("choiceH12"); end,
	function() 
	if _return == m1 then

		iscene("H12a")
	else
		iscene("H12b")
	end; end,
	function() 	iscene("H12c"); end,
	function() 	jump_out ("H13"); end
};

LABELS["H13"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("H13"); end,
	function() 	jump_out ("H14"); end
};

LABELS["H14"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("H14"); end,
	function() 	jump_out ("H15"); end
};

LABELS["H15"] = {
	function() 	iscene("H15"); end,
	function() 	jump_out ("H16"); end
};

LABELS["H16"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("H16"); end,
	function() 	jump_out ("H17"); end
};

LABELS["H17"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("H17"); end,
	function() 	jump_out ("H18"); end
};

LABELS["H18"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("H18"); end,
	function() 	jump_out ("H19"); end
};

LABELS["H19"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("H19"); end,
	function() 	jump_out ("H20"); end
};

LABELS["H20"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("H20"); end,
	function() 	imenu("choiceH20"); end,
	function() 
	if _return == m1 then

		iscene("H20_1")
	else
		iscene("H20_2")
	end; end,
	function() 	jump_out ("tc_act4_hanako"); end
};

LABELS["tc_act4_hanako"] = {
	function() 	act_op("tc_act4_hanako.mkv"); end,
	function() 	jump_out ("H21"); end
};

LABELS["H21"] = {
	function() 	iscene("H21"); end,
	function() 	jump_out ("H22"); end
};

LABELS["H22"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("H22"); end,
	function() 	imenu("choiceH22"); end,
	function() 
	if _return == m1 and seen_scene("H20_1") then

		iscene("H22a")
		jump_out ("H25")
	else
		if seen_scene("H20_1") then

			iscene("H22c")
			jump_out ("H24")
		else
			iscene("H22b")
		end
	end; end
};

LABELS["H23"] = {
	function() 	iscene("H23"); end,
	function() 	path_end("hanakorage", true); end,
	function() 	jump_out ("restart"); end
};

LABELS["H24"] = {
	function() 	iscene("H24"); end,
	function() 	path_end("hanakosad", true); end,
	function() 	jump_out ("restart"); end
};

LABELS["H25"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("H25"); end,
	function() 
	if seen_scene("H12a") then

		iscene("H25a")
	end; end,
	function() 	iscene("H25c"); end,
	function() 	jump_out ("H26"); end
};

LABELS["H26"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("H26"); end,
	function() 	jump_out ("H27"); end
};

LABELS["H27"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("H27"); end,
	function() 	jump_out ("H28"); end
};

LABELS["H28"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("H28"); end,
	function() 	jump_out ("H29"); end
};

LABELS["H29"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("H29"); end,
	function() 	iscene("H29h", true); end,
	function() 	iscene("H29x"); end,
	function() 	jump_out ("H30"); end
};

LABELS["H30"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("H30"); end,
	function() 	jump_out ("H31"); end
};

LABELS["H31"] = {
	function() 	iscene("H31"); end,
	function() 	path_end("hanako", true); end,
	function() 	jump_out ("restart"); end
};

LABELS["tc_act2_lilly"] = {
	function() 	act_op("tc_act2_lilly.mkv"); end,
	function() 	jump_out ("L1"); end
};

LABELS["L1"] = {
	function() 	iscene("L1"); end,
	function() 	jump_out ("L2"); end
};

LABELS["L2"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L2"); end,
	function() 	jump_out ("L3"); end
};

LABELS["L3"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L3"); end,
	function() 	jump_out ("L4"); end
};

LABELS["L4"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L4"); end,
	function() 	jump_out ("L5"); end
};

LABELS["L5"] = {
	function() 	iscene("L5"); end,
	function() 	jump_out ("L6"); end
};

LABELS["L6"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L6i"); end,
	function() 	imenu("choiceL6_1"); end,
	function() 
	if _return == m1 then

		iscene("L6a")
	else
		iscene("L6b")
	end; end,
	function() 	iscene("L6c"); end,
	function() 	jump_out ("L7"); end
};

LABELS["L7"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L7"); end,
	function() 	jump_out ("L8"); end
};

LABELS["L8"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L8"); end,
	function() 	jump_out ("tc_act3_lilly"); end
};

LABELS["tc_act3_lilly"] = {
	function() 	act_op("tc_act3_lilly.mkv"); end,
	function() 	jump_out ("L9"); end
};

LABELS["L9"] = {
	function() 	iscene("L9"); end,
	function() 	jump_out ("L10"); end
};

LABELS["L10"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L10"); end,
	function() 	imenu("choiceL10_1"); end,
	function() 
	if _return == m1 then

		iscene("L10a")
	else
		iscene("L10b")
	end; end,
	function() 	iscene("L10c"); end,
	function() 	imenu("choiceL10_2"); end,
	function() 
	if _return == m1 then

		iscene("L10d")
	else
		iscene("L10e")
	end; end,
	function() 	iscene("L10f"); end,
	function() 	jump_out ("L11"); end
};

LABELS["L11"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L11"); end,
	function() 	jump_out ("L12"); end
};

LABELS["L12"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L12"); end,
	function() 	jump_out ("L13"); end
};

LABELS["L13"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L13"); end,
	function() 	jump_out ("L14"); end
};

LABELS["L14"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L14"); end,
	function() 	jump_out ("L15"); end
};

LABELS["L15"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L15"); end,
	function() 	imenu("choiceL15"); end,
	function() 
	if _return == m1 then

		iscene("L15a")
	else
		iscene("L15b")
	end; end,
	function() 	iscene("L15c"); end,
	function() 	jump_out ("L16"); end
};

LABELS["L16"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L16"); end,
	function() 	jump_out ("L17"); end
};

LABELS["L17"] = {
	function() 	iscene("L17"); end,
	function() 	iscene("L17h", true, true); end,
	function() 	jump_out ("L18"); end
};

LABELS["L18"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L18"); end,
	function() 	jump_out ("L19"); end
};

LABELS["L19"] = {
	function() 	iscene("L19"); end,
	function() 	iscene("L19h", true); end,
	function() 	jump_out ("L20"); end
};

LABELS["L20"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L20"); end,
	function() 	imenu("choiceL20"); end,
	function() 
	if _return == m1 then

		iscene("L20a")
	else
		iscene("L20b")
	end; end,
	function() 	iscene("L20c"); end,
	function() 	jump_out ("tc_act4_lilly"); end
};

LABELS["tc_act4_lilly"] = {
	function() 	act_op("tc_act4_lilly.mkv"); end,
	function() 	jump_out ("L21"); end
};

LABELS["L21"] = {
	function() 	iscene("L21"); end,
	function() 	jump_out ("L22"); end
};

LABELS["L22"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L22"); end,
	function() 	jump_out ("L23"); end
};

LABELS["L23"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L23"); end,
	function() 	jump_out ("L24"); end
};

LABELS["L24"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L24"); end,
	function() 	imenu("choiceL24"); end,
	function() 
	if _return == m1 then

		iscene("L24a")
	else
		iscene("L24b")
	end; end,
	function() 	iscene("L24c"); end,
	function() 	jump_out ("L25"); end
};

LABELS["L25"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L25"); end,
	function() 	jump_out ("L26"); end
};

LABELS["L26"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L26"); end,
	function() 	iscene("L26h", true); end,
	function() 	iscene("L26x"); end,
	function() 	jump_out ("L27"); end
};

LABELS["L27"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L27"); end,
	function() 	jump_out ("L28"); end
};

LABELS["L28"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L28"); end,
	function() 	jump_out ("L29"); end
};

LABELS["L29"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L29"); end,
	function() 
	if seen_scene("L6b") and seen_scene("L15a") and seen_scene("L24a") then

		jump_out ("L30")
	else
		path_end("lilly")
		jump_out ("restart")
	end; end
};

LABELS["L30"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L30"); end,
	function() 	jump_out ("L31"); end
};

LABELS["L31"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("L31"); end,
	function() 	jump_out ("L32"); end
};

LABELS["L32"] = {
	function() 	iscene("L32"); end,
	function() 	path_end("lilly", true); end,
	function() 	jump_out ("L33"); end
};

LABELS["L33"] = {
	function() 	iscene("L33"); end,
	function() 	jump_out ("restart"); end
};

LABELS["tc_act2_emi"] = {
	function() 	act_op("tc_act2_emi.mkv"); end,
	function() 	jump_out ("E3"); end
};

LABELS["E3"] = {
	function() 	iscene("E3"); end,
	function() 	jump_out ("E4"); end
};

LABELS["E4"] = {
	function() 	iscene("E4"); end,
	function() 	jump_out ("E5"); end
};

LABELS["E5"] = {
	function() 	iscene("E5"); end,
	function() 	jump_out ("E6"); end
};

LABELS["E6"] = {
	function() 	iscene("E6"); end,
	function() 	jump_out ("E7"); end
};

LABELS["E7"] = {
	function() 	iscene("E7"); end,
	function() 	jump_out ("E8"); end
};

LABELS["E8"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("E8"); end,
	function() 	jump_out ("E9"); end
};

LABELS["E9"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("E9"); end,
	function() 	jump_out ("E10"); end
};

LABELS["E10"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("E10"); end,
	function() 	jump_out ("E11"); end
};

LABELS["E11"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("E11a"); end,
	function() 
	if seen_scene("A12") or seen_scene("A35a") then

		iscene("E11x")
	else
		iscene("E11y")
	end; end,
	function() 	iscene("E11z"); end,
	function() 	imenu("choiceE11"); end,
	function() 
	if _return == m1 then

		iscene("E11b")
	else
		iscene("E11c")
	end; end,
	function() 	iscene("E11d"); end,
	function() 	jump_out ("E12"); end
};

LABELS["E12"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("E12a"); end,
	function() 
	if seen_scene("E11b") then

		iscene("E12b")
	else
		iscene("E12c")
	end; end,
	function() 	iscene("E12d"); end,
	function() 	jump_out ("E13"); end
};

LABELS["E13"] = {
	function() 	iscene("E13"); end,
	function() 	jump_out ("E14"); end
};

LABELS["E14"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("E14"); end,
	function() 	jump_out ("E15"); end
};

LABELS["E15"] = {
	function() 	iscene("E15"); end,
	function() 	jump_out ("tc_act3_emi"); end
};

LABELS["tc_act3_emi"] = {
	function() 	act_op("tc_act3_emi.mkv"); end,
	function() 	jump_out ("E16"); end
};

LABELS["E16"] = {
	function() 	iscene("E16"); end,
	function() 	jump_out ("E17"); end
};

LABELS["E17"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("E17"); end,
	function() 	imenu("choiceE17"); end,
	function() 
	if _return == m1 then

		iscene("E17a")
	else
		iscene("E17b")
	end; end,
	function() 	iscene("E17x"); end,
	function() 	jump_out ("E18"); end
};

LABELS["E18"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("E18"); end,
	function() 
	if seen_scene("E17a") then

		iscene("E18a")
	else
		iscene("E18b")
	end; end,
	function() 	iscene("E18x"); end,
	function() 	jump_out ("E19"); end
};

LABELS["E19"] = {
	function() 	iscene("E19"); end,
	function() 	jump_out ("E20"); end
};

LABELS["E20"] = {
	function() 	iscene("E20"); end,
	function() 	iscene("E20h", true); end,
	function() 	iscene("E20x"); end,
	function() 	jump_out ("E21"); end
};

LABELS["E21"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("E21"); end,
	function() 	iscene("E21h", true); end,
	function() 	iscene("E21x"); end,
	function() 	jump_out ("E22"); end
};

LABELS["E22"] = {
	function() 	iscene("E22"); end,
	function() 	jump_out ("E23"); end
};

LABELS["E23"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("E23"); end,
	function() 	jump_out ("E24"); end
};

LABELS["E24"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("E24"); end,
	function() 	imenu("choiceE24"); end,
	function() 
	if _return == m1 then

		iscene("E24a")
	else
		iscene("E24b")
	end; end,
	function() 	iscene("E24c"); end,
	function() 	jump_out ("E25"); end
};

LABELS["E25"] = {
	function() 	iscene("E25"); end,
	function() 
	if seen_scene("E24a") then

		imenu("choiceE25")
		if _return == m1 then

			iscene("E25a")
		else
			iscene("E25b")
		end
	end; end,
	function() 	jump_out ("E26"); end
};

LABELS["E26"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("E26"); end,
	function() 
	if seen_scene("E25a") then

		iscene("E26a")
	end; end,
	function() 	iscene("E26b"); end,
	function() 
	if seen_scene("E25a") then

		iscene("E26e")
	end; end,
	function() 	iscene("E26f"); end,
	function() 
	if seen_scene("E24a") then

		imenu("choiceE26")
		if _return == m2 then

			iscene("E26d")
			jump_out ("tc_act4_emi")
		end
	end; end,
	function() 	jump_out ("E27"); end
};

LABELS["E27"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("E27"); end,
	function() 	imenu("choiceE27"); end,
	function() 
	if _return == m1 then

		iscene("E27a")
		path_end("emi")
		jump_out ("restart")
	end; end,
	function() 	iscene("E27b"); end,
	function() 	jump_out ("tc_act4_emi"); end
};

LABELS["tc_act4_emi"] = {
	function() 	act_op("tc_act4_emi.mkv"); end,
	function() 
	if seen_scene("E27b") then

		jump_out ("E30")
	end; end,
	function() 	jump_out ("E28"); end
};

LABELS["E28"] = {
	function() 	iscene("E28"); end,
	function() 	jump_out ("E29"); end
};

LABELS["E29"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("E29"); end,
	function() 	jump_out ("E30"); end
};

LABELS["E30"] = {
	function() 
	if seen_scene("E29") then

		iscene("timeskip")
	end; end,
	function() 	iscene("E30"); end,
	function() 
	if seen_scene("E29") then

		iscene("E30a")
	end; end,
	function() 	iscene("E30b"); end,
	function() 
	if seen_scene("E27") then

		iscene("E30c")
	else
		iscene("E30d")
	end; end,
	function() 	iscene("E30e"); end,
	function() 	jump_out ("E31"); end
};

LABELS["E31"] = {
	function() 	iscene("E31"); end,
	function() 	iscene("E31h", true); end,
	function() 	iscene("E31x"); end,
	function() 	jump_out ("E32"); end
};

LABELS["E32"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("E32"); end,
	function() 	path_end("emi", true); end,
	function() 	jump_out ("restart"); end
};

LABELS["tc_act2_rin"] = {
	function() 	act_op("tc_act2_rin.mkv"); end,
	function() 	jump_out ("R1"); end
};

LABELS["R1"] = {
	function() 	iscene("R1"); end,
	function() 	jump_out ("R2"); end
};

LABELS["R2"] = {
	function() 	iscene("R2"); end,
	function() 	imenu("choiceR2"); end,
	function() 
	if _return == m1 then

		iscene("R2a")
	else
		iscene("R2b")
	end; end,
	function() 	iscene("R2c"); end,
	function() 	jump_out ("R3"); end
};

LABELS["R3"] = {
	function() 	iscene("R3"); end,
	function() 	jump_out ("R4"); end
};

LABELS["R4"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R4"); end,
	function() 	jump_out ("R5"); end
};

LABELS["R5"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R5"); end,
	function() 	jump_out ("R6"); end
};

LABELS["R6"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R6"); end,
	function() 	imenu("choiceR6"); end,
	function() 
	if _return == m1 then

		iscene("R6a")
	else
		iscene("R6b")
	end; end,
	function() 	iscene("R6c"); end,
	function() 	jump_out ("R7"); end
};

LABELS["R7"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R7"); end,
	function() 	jump_out ("R8"); end
};

LABELS["R8"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R8"); end,
	function() 	jump_out ("R9"); end
};

LABELS["R9"] = {
	function() 	iscene("R9"); end,
	function() 	imenu("choiceR9"); end,
	function() 
	if _return == m1 then

		iscene("R9a")
	else
		iscene("R9b")
	end; end,
	function() 	iscene("R9c"); end,
	function() 	jump_out ("R10"); end
};

LABELS["R10"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R10"); end,
	function() 	jump_out ("R11"); end
};

LABELS["R11"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R11"); end,
	function() 
	if seen_scene("R2a") then

		if seen_scene("R6a") then

			if seen_scene("R9a") then

				imenu("choiceR11aaa")
			else
				imenu("choiceR11aab")
			end
			if seen_scene("R9a") then

				imenu("choiceR11aba")
			else
				imenu("choiceR11abb")
			end
		end
			if seen_scene("R9a") then

				imenu("choiceR11baa")
			else
				imenu("choiceR11bab")
			end
			if seen_scene("R9a") then

				imenu("choiceR11bba")
			else
				imenu("choiceR11bbb")
			end
		iscene("R11a")
		iscene("R11g")
	elseif _return == m2 then
		iscene("R11b")
		iscene("R11i")
	elseif _return == m3 then
		iscene("R11c")
		iscene("R11h")
	elseif _return == m4 then
		iscene("R11d")
		iscene("R11i")
	elseif _return == m5 then
		iscene("R11e")
		iscene("R11h")
	else
		iscene("R11f")
		iscene("R11g")
	end; end,
	function() 	iscene("R11j"); end,
	function() 	jump_out ("R12"); end
};

LABELS["R12"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R12"); end,
	function() 
	if seen_scene("A12") or seen_scene("A35a") then

		iscene("R12b")
	else
		iscene("R12a")
	end; end,
	function() 	iscene("R12c"); end,
	function() 
	if seen_scene("A12") or seen_scene("A35a") then

		iscene("R12e")
	else
		iscene("R12d")
	end; end,
	function() 	iscene("R12f"); end,
	function() 	jump_out ("R13"); end
};

LABELS["R13"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R13"); end,
	function() 	jump_out ("R14"); end
};

LABELS["R14"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R14"); end,
	function() 	jump_out ("R15"); end
};

LABELS["R15"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R15"); end,
	function() 	jump_out ("R16"); end
};

LABELS["R16"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R16"); end,
	function() 	imenu("choiceR16"); end,
	function() 
	if _return == m1 then

		iscene("R16a")
	else
		iscene("R16b")
	end; end,
	function() 	iscene("R16c"); end,
	function() 
	if seen_scene("R11g") then

		iscene("R16d")
	end; end,
	function() 	iscene("R16e"); end,
	function() 	jump_out ("tc_act3_rin"); end
};

LABELS["tc_act3_rin"] = {
	function() 	act_op("tc_act3_rin.mkv"); end,
	function() 	jump_out ("R17"); end
};

LABELS["R17"] = {
	function() 	iscene("R17"); end,
	function() 	jump_out ("R18"); end
};

LABELS["R18"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R18"); end,
	function() 	jump_out ("R19"); end
};

LABELS["R19"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R19"); end,
	function() 
	if seen_scene("R16b") then

		iscene("R19a")
	end; end,
	function() 	iscene("R19b"); end,
	function() 
	if seen_scene("R16d") then

		jump_out ("R20")
	else
		jump_out ("R21")
	end; end
};

LABELS["R20"] = {
	function() 	iscene("R20"); end,
	function() 	imenu("choiceR20"); end,
	function() 
	if _return == m1 then

		iscene("R20a")
	else
		iscene("R20b")
	end; end,
	function() 	iscene("R20c"); end,
	function() 	jump_out ("R22"); end
};

LABELS["R21"] = {
	function() 	iscene("R21"); end,
	function() 	imenu("choiceR21"); end,
	function() 
	if _return == m1 then

		iscene("R21a")
	else
		iscene("R21b")
	end; end,
	function() 	iscene("R21c"); end,
	function() 	jump_out ("R22"); end
};

LABELS["R22"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R22"); end,
	function() 	jump_out ("R23"); end
};

LABELS["R23"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R23"); end,
	function() 	jump_out ("R23_2"); end
};

LABELS["R23_2"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R23_2"); end,
	function() 	jump_out ("R24"); end
};

LABELS["R24"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R24"); end,
	function() 	jump_out ("R25"); end
};

LABELS["R25"] = {
	function() 	iscene("R25"); end,
	function() 	jump_out ("R26"); end
};

LABELS["R26"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R26"); end,
	function() 	imenu("choiceR26"); end,
	function() 
	if _return == m1 then

		iscene("R26a")
	else
		iscene("R26b")
	end; end,
	function() 	iscene("R26c"); end,
	function() 	jump_out ("R27"); end
};

LABELS["R27"] = {
	function() 	iscene("R27"); end,
	function() 	iscene("R27h", true); end,
	function() 	iscene("R27x"); end,
	function() 	jump_out ("R28"); end
};

LABELS["R28"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R28"); end,
	function() 
	if(seen_scene("R20a") or seen_scene("R21a")) then

		imenu("choiceR28_1")
	else
		imenu("choiceR28_2")
	end; end,
	function() 
	if _return == m1 then

		iscene("R28a")
	elseif _return == m2 then
		iscene("R28b")
	else
		jump_out ("R29")
	end; end,
	function() 	iscene("R28c"); end,
	function() 	jump_out ("tc_act4_rin"); end
};

LABELS["R29"] = {
	function() 	iscene("R29"); end,
	function() 	path_end("rin", false); end,
	function() 	jump_out ("restart"); end
};

LABELS["tc_act4_rin"] = {
	function() 	act_op("tc_act4_rin.mkv"); end,
	function() 	jump_out ("R30"); end
};

LABELS["R30"] = {
	function() 	iscene("R30"); end,
	function() 
	if(seen_scene("R16d")) then

		iscene("R30x")
	else
		iscene("R30y")
	end; end,
	function() 	iscene("R30z"); end,
	function() 	jump_out ("R31"); end
};

LABELS["R31"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R31"); end,
	function() 	jump_out ("R32"); end
};

LABELS["R32"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R32"); end,
	function() 	imenu("choiceR32"); end,
	function() 
	if _return == m1 then

		iscene("R32a")
		jump_out ("R35")
	end; end,
	function() 	iscene("R32b"); end,
	function() 	jump_out ("R34"); end
};

LABELS["R34"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R33"); end,
	function() 	iscene("R34"); end,
	function() 	jump_out ("R38"); end
};

LABELS["R35"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R33"); end,
	function() 	iscene("R35"); end,
	function() 	jump_out ("R36"); end
};

LABELS["R36"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R36"); end,
	function() 
	if not seen_scene("R19a") then

		iscene("R36a")
	end; end,
	function() 	iscene("R36x"); end,
	function() 	jump_out ("R37"); end
};

LABELS["R37"] = {
	function() 	iscene("R37"); end,
	function() 	path_end("rintrue", true); end,
	function() 	jump_out ("restart"); end
};

LABELS["R38"] = {
	function() 	iscene("R38"); end,
	function() 	jump_out ("R39"); end
};

LABELS["R39"] = {
	function() 	iscene("R39"); end,
	function() 	jump_out ("R40"); end
};

LABELS["R40"] = {
	function() 	iscene("R40"); end,
	function() 	jump_out ("R41"); end
};

LABELS["R41"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("R41"); end,
	function() 	iscene("R41h", true); end,
	function() 	jump_out ("R42"); end
};

LABELS["R42"] = {
	function() 	iscene("R42"); end,
	function() 	path_end("rin", true); end,
	function() 	jump_out ("restart"); end
};

LABELS["tc_act2_shizune"] = {
	function() 	act_op("tc_act2_shizune.mkv"); end,
	function() 	jump_out ("S8"); end
};

LABELS["S8"] = {
	function() 	iscene("S8"); end,
	function() 	jump_out ("S9"); end
};

LABELS["S9"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S9"); end,
	function() 	jump_out ("S10"); end
};

LABELS["S10"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S10"); end,
	function() 	jump_out ("S11"); end
};

LABELS["S11"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S11"); end,
	function() 	jump_out ("S12"); end
};

LABELS["S12"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S12"); end,
	function() 	jump_out ("S13"); end
};

LABELS["S13"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S13"); end,
	function() 	jump_out ("S14"); end
};

LABELS["S14"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S14"); end,
	function() 	jump_out ("S15"); end
};

LABELS["S15"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S15"); end,
	function() 	jump_out ("S16"); end
};

LABELS["S16"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S16"); end,
	function() 	jump_out ("tc_act3_shizune"); end
};

LABELS["tc_act3_shizune"] = {
	function() 	act_op("tc_act3_shizune.mkv"); end,
	function() 	jump_out ("S17"); end
};

LABELS["S17"] = {
	function() 	iscene("S17"); end,
	function() 
	if seen_scene("A26b") then

		iscene("S17a")
	end; end,
	function() 	iscene("S17x"); end,
	function() 	jump_out ("S18"); end
};

LABELS["S18"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S18"); end,
	function() 	jump_out ("S19"); end
};

LABELS["S19"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S19"); end,
	function() 	jump_out ("S20"); end
};

LABELS["S20"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S20"); end,
	function() 	jump_out ("S21"); end
};

LABELS["S21"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S21"); end,
	function() 	jump_out ("S22"); end
};

LABELS["S22"] = {
	function() 	iscene("S22"); end,
	function() 
	if seen_scene("A26b") then

		iscene("S22a")
	else
		iscene("S22b")
	end; end,
	function() 	iscene("S22c"); end,
	function() 	iscene("S22h", true); end,
	function() 	iscene("S22x"); end,
	function() 	jump_out ("S23"); end
};

LABELS["S23"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S23"); end,
	function() 
	if not seen_scene("A2b") then

		iscene("S23a")
	end; end,
	function() 	iscene("S23x"); end,
	function() 	jump_out ("S24"); end
};

LABELS["S24"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S24"); end,
	function() 	jump_out ("S25"); end
};

LABELS["S25"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S25"); end,
	function() 	jump_out ("S26"); end
};

LABELS["S26"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S26"); end,
	function() 
	if seen_scene("A26b") then

		iscene("S26a")
	else
		iscene("S26b")
	end; end,
	function() 	iscene("S26c"); end,
	function() 	jump_out ("S27"); end
};

LABELS["S27"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S27"); end,
	function() 	jump_out ("S28"); end
};

LABELS["S28"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S28"); end,
	function() 	imenu("choiceS28"); end,
	function() 
	if _return == m1 then

		iscene("S28a")
		iscene("S28h", true)
		jump_out ("S29_1")
	else
		iscene("S28b")
	end; end,
	function() 	jump_out ("S29_2"); end
};

LABELS["S29_1"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S29"); end,
	function() 	iscene("S29a"); end,
	function() 	iscene("S29x"); end,
	function() 	iscene("S29xa"); end,
	function() 	iscene("S29y"); end,
	function() 	iscene("S29ya"); end,
	function() 	jump_out ("tc_act4_shizune"); end
};

LABELS["S29_2"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S29"); end,
	function() 	iscene("S29b"); end,
	function() 	iscene("S29x"); end,
	function() 	iscene("S29xb"); end,
	function() 
	if seen_scene("A26b") then

		iscene("S29xba")
	else
		iscene("S29xbb")
	end; end,
	function() 	iscene("S29xbc"); end,
	function() 	iscene("S29y"); end,
	function() 	iscene("S29yb"); end,
	function() 	jump_out ("tc_act4_shizune"); end
};

LABELS["tc_act4_shizune"] = {
	function() 	act_op("tc_act4_shizune.mkv"); end,
	function() 	jump_out ("S30"); end
};

LABELS["S30"] = {
	function() 	iscene("S30"); end,
	function() 	jump_out ("S31"); end
};

LABELS["S31"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S31"); end,
	function() 	jump_out ("S32"); end
};

LABELS["S32"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S32"); end,
	function() 	jump_out ("S33"); end
};

LABELS["S33"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S33"); end,
	function() 
	if seen_scene("S28a") then

		jump_out ("S38")
	end; end,
	function() 	jump_out ("S34"); end
};

LABELS["S34"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S34"); end,
	function() 
	if not seen_scene("A26b") then

		iscene("S34a")
	else
		iscene("S34b")
	end; end,
	function() 	iscene("S34c"); end,
	function() 	jump_out ("S35"); end
};

LABELS["S35"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S35"); end,
	function() 	iscene("S35h", true); end,
	function() 	iscene("S35x"); end,
	function() 	jump_out ("S36"); end
};

LABELS["S36"] = {
	function() 	iscene("S36"); end,
	function() 	jump_out ("S37"); end
};

LABELS["S37"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S37"); end,
	function() 	path_end("shizune", true); end,
	function() 	jump_out ("restart"); end
};

LABELS["S38"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S38"); end,
	function() 	jump_out ("S39"); end
};

LABELS["S39"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S39"); end,
	function() 	jump_out ("S40"); end
};

LABELS["S40"] = {
	function() 	iscene("timeskip"); end,
	function() 	iscene("S40"); end,
	function() 	path_end("shizune"); end,
	function() 	jump_out ("restart"); end
};